### PR TITLE
Fixes an issue registering the plugin

### PR DESCRIPTION
**Pull request by bryansray**
I'm not entirely sure the details of this, but it seems to get the plugin working again.

Please let me know if there is anything else I can do to help. Thanks for the addon!

Resolves issue #2

### CODE REVIEW

**Comment by chkmyid** [comment]
I tested this method. It seems to be working very well. I got a hint from @bryansray 's modified code and patched the Bagnon_Facade module addon. Thank you for helping me.

**Comment by CMcFadyen** [comment]
This does not fix it for me, it just gives me:
Bagnon_ItemLevel\main.lua:15: attempt to index local 'Addon'

**Comment by bryansray** [comment]
> This does not fix it for me, it just gives me:
> Bagnon_ItemLevel\main.lua:15: attempt to index local 'Addon'

@CMcFadyen How did you update your `main.lua` file? Could you paste your updated file in a gist for me? Also, are you using any other Bagnon Plugins? If so, could you try disabling them and only load Bagnon and Bagnon_ItemLevel?

**Comment by CMcFadyen** [comment]
I manually changed the file based on the diff

**Comment by bryansray** [comment]
> I manually changed the file based on the diff

@CMcFadyen could you post a gist of your `Bagnon_ItemLevel\main.lua` file?

**Comment by CMcFadyen** [comment]
https://gist.github.com/CMcFadyen/10b6615568460a049380e707e7127833

**Comment by bryansray** [comment]
@CMcFadyen Yeah, that all looks right. Things I would recommend you try:

1. Check to see if you have any other Bagnon Plugins installed and running? If so, try disabling them. See if that helps.
2. Make sure you have the latest version of `Bagnon` installed as well.
3. Maybe try closing WoW down all the way and starting it up again
4. Last resort may be clearing out your WoW cache folders (highly unlikely fix, in my opinion)

**Comment by CMcFadyen** [comment]
I disabled all addons except Bagnon and this, and I was getting a Blizzard frame error.  Restarting WoW resolved everything and it's working now.  Thanks for the help.

**Comment by Zywicki** [comment]
Spend a few hours myself to try and figure out how to get working item level display. This fix worked perfectly, thanks.

**Comment by bryansray** [comment]
Happy to help. Hoping that it may get merged in soon.

**Comment by goldpaw** [comment]
I fixed this another way.

**Pull request closed without merging**
